### ISSUE TITLE
pyDynamo for windows - visual studio error

### ISSUE THREAD

**Issue by fieryzarzar** [ubcbraincircuits/pyDynamo#8]
Hi! I'm trying to install pyDynamo on Windows but I keep receiving an error message of "Failed building wheel for morphio" preceded by the error message below. This is despite installing the latest Visual Studio version enabled with "Desktop development with C++".

```
CMake Error at CMakeLists.txt:2 (project):
    Generator
      Visual Studio 15 2017 Win64
    could not find any instance of Visual Studio.
  -- Configuring incomplete, errors occurred!
```
Thanks in advance!

**Comment by Peter-Hogg** [comment]
> 
> 
> Thank you, this works!!! With your fix, I was able to open a .mat of a previously constructed neuron in Matlab Dynamo into PyDynamo and use the '3' and 'M' function for visualisation and listing changes between stacks (added, subtracted, transition, extension, retraction). I was wondering if you could confirm that the added + subtracted are for filaments only (<10 micron), transition are filo --> branches, and extension + retraction is for everything?
> 
> Also, I would like to do further analysis but just wanted to confirm that the current PyDynamo version doesn't yet have all of the analysis such as TDBL, filopodia lifetime / survival, motility, etc., correct?
> 
> Thanks, again!

It has some basic metrics (new branches, eliminations, TDBL etc) and more complex analysis can be performed on the exported data tables. Advance analysis is supported by importing dynamo as a python library to interact with the tree structures directly.
